codecov:
  require_ci_to_pass: yes
  token: d3529014-9a00-4ef4-8d72-1fc925ea4e65

coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: 82%
        threshold: 6%
    patch:
      default:
        target: auto
        threshold: 6%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
